# Generated by Django 2.0.7 on 2018-08-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20180801_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='Number',
            field=models.IntegerField(default=20),
        ),
    ]
