# Generated by Django 2.0.7 on 2018-08-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20180801_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='date',
            field=models.DateField(default=0.0005508262393590386),
        ),
    ]
